services:
     cuaround_user.registration.form.type:
        class: Cuaround\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cuaround_user_registration }
            
     cuaround_user.profile.form.type:
        class: Cuaround\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cuaround_user_profile }
            
     cuaround_user.my_user_manager:
        class: Cuaround\UserBundle\Extension\MyUserManager
        public: false
        parent: fos_user.user_manager.default
            
     cuaround_user.form.handler.registration:
        class: Cuaround\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
        
     cuaround_user.form.handler.profile:
        class: Cuaround\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false