services:
     ventouris_user.registration.form.type:
        class: Ventouris\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ventouris_user_registration }
            
     ventouris_user.profile.form.type:
        class: Ventouris\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ventouris_user_profile }
            
     ventouris_user.my_user_manager:
        class: Ventouris\UserBundle\Extension\MyUserManager
        public: false
        parent: fos_user.user_manager.default
            
     ventouris_user.form.handler.registration:
        class: Ventouris\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false
        
     ventouris_user.form.handler.profile:
        class: Ventouris\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false